default: &default
  adapter: postgresql
  encoding: unicode
  timeout: 5000

development:
  <<: *default
  host: <%= ENV['DATABASE_HOST'] %>  
  port: <%= ENV['DATABASE_PORT'] || "5432" %>  
  database: <%= ENV['DATABASE_DEVELOPMENT_NAME'] %>  
  username: <%= ENV['DATABASE_USERNAME'] %>  
  pool: 5

test:
  <<: *default
  host: <%= ENV['DATABASE_HOST'] %>  
  port: <%= ENV['DATABASE_PORT'] || "5432" %>  
  database: <%= ENV['DATABASE_TEST_NAME'] %>  
  username: <%= ENV['DATABASE_USERNAME'] %>  
  pool: 5

production:
  <<: *default
  host: <%= ENV['DATABASE_HOST'] %>  
  port: <%= ENV['DATABASE_PORT'] || "5432" %>  
  database: <%= ENV['DATABASE_PRODUCTION_NAME'] %>  
  username: <%= ENV['DATABASE_USERNAME'] %>  
  password: <%= ENV['DATABASE_PASSWORD'] %>  
  pool: 25
