# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e508cf6dd351de610900b1cebbf11f63adaac4d788e64d80baf34c8e9b6afc29dee396d2637ea94fc69ca00d89409030a5559bd1dd7d31ec02fff13f092e10a4

test:
  secret_key_base: 31012f94d8aff66aef2a3e92398e49a34f45fa11801e2c829a4412e33376f594a781f604ac0f73f5f06e272f5f320404595183094d00a98b11458d7be54e5815

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
