# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4321fc473a771414a791da07c8a6e8fdfe07fa556a5b88b72380039ae529d0fedfb5352d3c3c4bcfe02a58b09c5df60643d0696fc30c272da3cc5553df648b29

test:
  secret_key_base: d17ba4444da3e24a8cae7855226c823bcddafa4b7848c23d7dc2739e0abd1e20f111986dbd5bc7daa997b80fd3e15bbc0d7f184b42c3924f84e3388c8418ec6f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
